name: meschane-of-taganrog

services:
  frontend:
    container_name: meschane-of-taganrog_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    

  backend:
    container_name: meschane-of-taganrog_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
